#!/usr/bin/env bash
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
python dqn_agent.py
